In [1]:
import numpy as np

In [22]:
#creating array
np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 8]])  #array with list
np.array(((5, 2, 7), (3, 8, 9)))  #array with tuples
np.zeros((2, 3)) #array with value zero
np.full((3, 3), 3, dtype = 'complex') #ARRAY with single value
np.random.random((3, 2))  #array of random values
np.arange(1, 9, 2).reshape(4, 1)  #array from range

arr= np.arange(1, 9).reshape(2, 4) #2-D array
arr.flatten() #falttening 2-D array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
#Array indexing
#basic indexing, integer and slice is used
arr= np.arange(1, 9).reshape(2, 4)

#indexing with integer
print(arr[0][1], arr[1], sep= ", ", end=" \n\n")  #this will give 1-D array

#indexing with slice
print(arr[:, 2:], arr[0:1, :2], sep= ", ", end= "\n\n")

#indexing with slice and integer
print(arr[:, 2], arr[1, :2]) #this will give 1-D array

2, [5 6 7 8] 

[[3 4]
 [7 8]], [[1 2]]

[3 7] [5 6]


In [47]:
#advance indexing
arr= np.arange(1, 9).reshape(2, 4)
print(arr, end= "\n\n")

# integer array indexing
# 1)
print(arr[[1, 0], [2, 1]], end= "\n\n")

# 2)
row= [[0,0], [1,1]] 
col= [[0, 3], [0, 3]]
print(arr[row, col], end="\n\n")   #corresponding row col

#boolean indexing
print(arr[arr%2==0]) #give 1-D array

[[1 2 3 4]
 [5 6 7 8]]

[7 2]

[[1 4]
 [5 8]]

[2 4 6 8]
