In [1]:
import numpy as np

In [3]:
arr= np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr1= np.array([[8], [6], [3]])
arr1

array([[8],
       [6],
       [3]])

      R    C
arr   3    3
arr1  3    1

Either both values should be same or 1 value should be 1
arr and arr1 are broadcastable
we can apply operations on them

In [8]:
arr+arr1

array([[ 9, 10, 11],
       [10, 11, 12],
       [10, 11, 12]])

In [9]:
arr-arr1

array([[-7, -6, -5],
       [-2, -1,  0],
       [ 4,  5,  6]])

In [10]:
arr*arr1

array([[ 8, 16, 24],
       [24, 30, 36],
       [21, 24, 27]])

In [13]:
arr2= np.array([1, 2])
#arr and arr2 are not broadcastable
arr+arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 