In [49]:
import numpy as np


In [58]:
rng= np.random.default_rng(seed= 3)   #seed is use to generate same random values
col1 = rng.integers(low=3, high=9, size=(10, 1))
col2 = rng.integers(low=5, high=15, size=(10, 1))
col3 = 3*col1 + 4*col2+ rng.random(size=(10, 1))
arr= np.concatenate((col1, col2, col3), axis=1)

In [59]:
arr

array([[ 7.        ,  8.        , 53.39122819],
       [ 3.        ,  9.        , 45.51674018],
       [ 4.        , 11.        , 56.43062802],
       [ 4.        ,  9.        , 48.58679857],
       [ 4.        ,  7.        , 40.73783779],
       [ 7.        ,  6.        , 45.95626725],
       [ 8.        , 11.        , 68.28420116],
       [ 6.        , 12.        , 66.64854721],
       [ 3.        ,  5.        , 29.696216  ],
       [ 3.        ,  6.        , 33.29272075]])

In [74]:
#70 and 30% of array arr
arr1= rng.permutation(arr)
rows= arr1.shape[0]
p1=0.7
print(arr1[:int(rows*p1), :])
print(arr1[int(rows*p1):, :])


[[ 8.         11.         68.28420116]
 [ 4.          9.         48.58679857]
 [ 3.          5.         29.696216  ]
 [ 7.          8.         53.39122819]
 [ 7.          6.         45.95626725]
 [ 3.          9.         45.51674018]
 [ 4.          7.         40.73783779]]
[[ 4.         11.         56.43062802]
 [ 6.         12.         66.64854721]
 [ 3.          6.         33.29272075]]


In [ ]:
ind= rng.permutation(np.arange(10))
print(arr1[: :])
print(arr1[int(rows*p1):, :])