In [1]:
import numpy as np

In [7]:
arr= np.arange(1,10).reshape(3,3)
arr1= np.array([[3], [6], [9]])
print(arr, arr1, sep= "\n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3]
 [6]
 [9]]


In [8]:
np.add(arr, arr1)

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [9]:
np.subtract(arr, arr1)

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [10]:
np.multiply(arr, arr1)

array([[ 3,  6,  9],
       [24, 30, 36],
       [63, 72, 81]])

In [12]:
np.negative(arr)

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [13]:
np.power(arr, arr1)

array([[        1,         8,        27],
       [     4096,     15625,     46656],
       [ 40353607, 134217728, 387420489]])